# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
